-- Quality API mappings (Radarr/Sonarr)

INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Unknown', 'radarr', 'Unknown');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Unknown', 'sonarr', 'Unknown');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('SDTV', 'radarr', 'SDTV');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('SDTV', 'sonarr', 'SDTV');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('DVD', 'radarr', 'DVD');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('DVD', 'sonarr', 'DVD');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('DVD-R', 'radarr', 'DVD-R');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('DVD-R', 'sonarr', 'DVD-R');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('DVDSCR', 'radarr', 'DVDSCR');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('DVDSCR', 'sonarr', 'DVDSCR');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('REGIONAL', 'radarr', 'REGIONAL');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('REGIONAL', 'sonarr', 'REGIONAL');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('HDTV', 'radarr', 'HDTV');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('HDTV', 'sonarr', 'HDTV');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('HDTV-720p', 'radarr', 'HDTV-720p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('HDTV-720p', 'sonarr', 'HDTV-720p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('HDTV-1080p', 'radarr', 'HDTV-1080p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('HDTV-1080p', 'sonarr', 'HDTV-1080p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('HDTV-2160p', 'radarr', 'HDTV-2160p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('HDTV-2160p', 'sonarr', 'HDTV-2160p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('WEBDL-480p', 'radarr', 'WEBDL-480p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('WEBDL-480p', 'sonarr', 'WEBDL-480p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('WEBDL-720p', 'radarr', 'WEBDL-720p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('WEBDL-720p', 'sonarr', 'WEBDL-720p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('WEBDL-1080p', 'radarr', 'WEBDL-1080p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('WEBDL-1080p', 'sonarr', 'WEBDL-1080p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('WEBDL-2160p', 'radarr', 'WEBDL-2160p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('WEBDL-2160p', 'sonarr', 'WEBDL-2160p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('WEBRip-480p', 'radarr', 'WEBRip-480p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('WEBRip-480p', 'sonarr', 'WEBRip-480p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('WEBRip-720p', 'radarr', 'WEBRip-720p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('WEBRip-720p', 'sonarr', 'WEBRip-720p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('WEBRip-1080p', 'radarr', 'WEBRip-1080p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('WEBRip-1080p', 'sonarr', 'WEBRip-1080p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('WEBRip-2160p', 'radarr', 'WEBRip-2160p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('WEBRip-2160p', 'sonarr', 'WEBRip-2160p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Bluray-480p', 'radarr', 'Bluray-480p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Bluray-480p', 'sonarr', 'Bluray-480p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Bluray-576p', 'radarr', 'Bluray-576p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Bluray-576p', 'sonarr', 'Bluray-576p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Bluray-720p', 'radarr', 'Bluray-720p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Bluray-720p', 'sonarr', 'Bluray-720p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Bluray-1080p', 'radarr', 'Bluray-1080p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Bluray-1080p', 'sonarr', 'Bluray-1080p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Bluray-2160p', 'radarr', 'Bluray-2160p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Bluray-2160p', 'sonarr', 'Bluray-2160p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Bluray-1080p Remux', 'radarr', 'Bluray-1080p Remux');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Bluray-1080p Remux', 'sonarr', 'Bluray-1080p Remux');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Bluray-2160p Remux', 'radarr', 'Bluray-2160p Remux');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Bluray-2160p Remux', 'sonarr', 'Bluray-2160p Remux');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Remux-1080p', 'radarr', 'Remux-1080p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Remux-1080p', 'sonarr', 'Remux-1080p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Remux-2160p', 'radarr', 'Remux-2160p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Remux-2160p', 'sonarr', 'Remux-2160p');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('BR-DISK', 'radarr', 'BR-DISK');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('BR-DISK', 'sonarr', 'BR-DISK');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Raw-HD', 'radarr', 'Raw-HD');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('Raw-HD', 'sonarr', 'Raw-HD');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('CAM', 'radarr', 'CAM');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('CAM', 'sonarr', 'CAM');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('TELESYNC', 'radarr', 'TELESYNC');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('TELESYNC', 'sonarr', 'TELESYNC');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('TELECINE', 'radarr', 'TELECINE');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('TELECINE', 'sonarr', 'TELECINE');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('WORKPRINT', 'radarr', 'WORKPRINT');
INSERT OR IGNORE INTO quality_api_mappings (quality_name, arr_type, api_name) VALUES ('WORKPRINT', 'sonarr', 'WORKPRINT');
